packages:
  - apps/*
  - packages/*
catalog:
  date-fns: ^4.1.0
  date-fns-tz: ^3.2.0
  dotenv: ^17.3.1
  react: ^19.2.4
  zod: ^4.3.6
  typescript: ^5
  "@trpc/server": ^11.10.0
  "@trpc/client": ^11.10.0
  "@trpc/tanstack-react-query": ^11.10.0
  "@tanstack/react-query": ^5.90.21
  "@prisma/client": ^7.4.1
  "@prisma/adapter-pg": ^7.4.1
  "@prisma/adapter-mariadb": ^7.4.1
  prisma: ^7.4.1
  pg: ^8.18.0
  better-auth: ^1.4.18
  "@better-auth/expo": ^1.4.18
  "@better-auth/passkey": ^1.4.18
  "@types/pg": ^8.15.6
