// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// This module is the single source of truth for PDFX styling tokens.
// Update the exported `theme` object to customize component styles.

interface PdfxTheme {
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  name: string;
  page: {
    size: "A4" | "LETTER" | "LEGAL";
    orientation: "portrait" | "landscape";
  };
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: {
      regular: number;
      medium: number;
      semibold: number;
      bold: number;
    };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: {
      none: number;
      sm: number;
      md: number;
      lg: number;
      full: number;
    };
    letterSpacing: {
      tight: number;
      normal: number;
      wide: number;
      wider: number;
    };
  };
  spacing: {
    page: {
      marginTop: number;
      marginRight: number;
      marginBottom: number;
      marginLeft: number;
    };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: {
        h1: number;
        h2: number;
        h3: number;
        h4: number;
        h5: number;
        h6: number;
      };
    };
  };
}

export const theme: PdfxTheme = {
  name: "minimal",

  // Primitive scales.
  primitives: {
    typography: {
      xs: 10,
      sm: 12,
      base: 15,
      lg: 18,
      xl: 22,
      "2xl": 28,
      "3xl": 36,
    },
    spacing: {
      0: 0,
      0.5: 2,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      8: 32,
      10: 40,
      12: 48,
      16: 64,
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.6,
    },
    borderRadius: {
      none: 0,
      sm: 2,
      md: 4,
      lg: 8,
      full: 9999,
    },
    letterSpacing: {
      tight: -0.025,
      normal: 0,
      wide: 0.025,
      wider: 0.05,
    },
  },

  // Semantic colors. Values must be valid for react-pdf.
  colors: {
    foreground: "#18181b",
    background: "#ffffff",
    muted: "#fafafa",
    mutedForeground: "#a1a1aa",
    primary: "#18181b",
    primaryForeground: "#ffffff",
    border: "#e4e4e7",
    accent: "#71717a",
    destructive: "#b91c1c",
    success: "#15803d",
    warning: "#a16207",
    info: "#0369a1",
  },

  // Typography defaults.
  typography: {
    body: {
      fontFamily: "Helvetica",
      fontSize: 11,
      lineHeight: 1.65,
    },
    heading: {
      fontFamily: "Courier",
      fontWeight: 600,
      lineHeight: 1.25,
      fontSize: {
        h1: 24,
        h2: 20,
        h3: 16,
        h4: 14,
        h5: 12,
        h6: 10,
      },
    },
  },

  // Layout spacing.
  spacing: {
    page: {
      marginTop: 72,
      marginRight: 56,
      marginBottom: 72,
      marginLeft: 56,
    },
    sectionGap: 36,
    paragraphGap: 14,
    componentGap: 18,
  },

  // Page defaults.
  page: {
    size: "A4",
    orientation: "portrait",
  },
};
